config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  post 'meeting_schedule_candidate/create'
  delete 'meeting_schedule_anchor/:id/destroy', to: 'meeting_schedule_anchor#destroy'
  post 'meeting_schedule_confirm/anchor/:anchor_id/candidate/:candidate_id/create', to: 'meeting_schedule_confirm#create'

  get 'home/index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i[create destroy]
  resources :home
end

app/controllers/home_controller.rb
# ログイン画面を表示するためのコントローラ
class HomeController < ApplicationController
  skip_before_action :strict_logged_in, only: :index

  def index
    if current_user.present?
      @meeting_schedule_anchors =
        MeetingSchedule::Anchor.where(user: current_user.id)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
/ NOTE: 現在の実装だと「入力作業を終えて submit」「submit 後には候補日のコピペ欄が空白になり利用できない」流れになっている

h1 Home#index

- if current_user.present?
  = form_with url: meeting_schedule_candidate_create_path, method: :post do |f|
    p
      - 3.times.with_index(1) do |_, i|
        = f.fields_for 'meeting_schedule_candidate[]', MeetingSchedule::Candidate.new do |m|
          = m.label :date, "#{t('helpers.label.meeting_schedule_candidate.date')} #{i}: "
          = m.date_field :date, class: 'js-apply-date-select-from'
          br
    p 開始時刻 → 14:00〜17:00 の間で固定
    p
      = f.fields_for 'meeting_schedule_candidate[]', MeetingSchedule::Candidate.new do |m|
        = m.label :description
        br
        = m.text_area :description, cols: 55, rows: 10, placeholder: "(〇〇サービス経由で紹介を受ける)\n\n△△会社名\n\n☓☓サービスを展開"
        br
    p
      = label_tag :copay_and_paste, 'コピペ欄:'
      br
      / 候補日を選択したとき JS イベントを発火させて <textarea/> の内容を差し替える (選択候補日と 希望日とを対応させる)
      = text_area_tag :copay_and_paste, '', cols: 55, rows: 5, readonly: true, class: 'js-apply-date-select-to', placeholder: "1. n月m日 (月) 14:00〜17:00 に開始\n2. n月m日 (月) 14:00〜17:00 に開始\n3. n月m日 (月) 14:00〜17:00 に開始"
    p
      = f.submit
  h2 候補日群

  p
    - @meeting_schedule_anchors.each do |meeting_schedule_anchor|
      p
        h3
          / 候補日に記録してある description の中身を数行だけ表示する
          - meeting_schedule_anchor.description_summary.each do |line|
            = line
            br
          = button_to '候補日群を削除する', "/meeting_schedule_anchor/#{meeting_schedule_anchor.id}/destroy", method: :delete
        ul
          - meeting_schedule_anchor.meeting_schedule_candidates.each do |candidate|
            li
              = l candidate.date
              = button_to '確定する', "/meeting_schedule_confirm/anchor/#{meeting_schedule_anchor.id}/candidate/#{candidate.id}/create"
              br
      hr